language: php

php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm

sudo: required

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install Pygments==1.6

before_script:
  - composer require --no-update satooshi/php-coveralls:0.6.1
  - composer update --dev --no-interaction

script:
  - mkdir -p build/logs
  - ./vendor/bin/phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - php vendor/bin/coveralls
