language: php

sudo: required

php:
  - 7.1
  - 7.0
  - 5.6
  - hhvm
  - nightly

matrix:
  allow_failures:
    - php: nightly

before_install:
  - sudo pip install --upgrade pip
  - sudo pip install Pygments==1.6
  - travis_retry composer self-update

install:
  - travis_retry composer require --no-update satooshi/php-coveralls:^1.0
  - travis_retry composer install --no-interaction --prefer-dist

before_script:
  - mkdir -p build/logs

script:
  - ./vendor/bin/parallel-lint src tests
  - ./vendor/bin/phpunit --verbose --coverage-clover build/logs/clover.xml
  - ./vendor/bin/phpcs src tests --standard=psr2 -sp

after_success:
  - travis_retry php vendor/bin/coveralls
